###P3.1

![P3.1](https://drive.google.com/uc?id=1YYCRQis1-aCK0iB7z48a73vJptrXT5Dh)

###P3.3
![P3.3](https://drive.google.com/uc?id=1WaIxvuukbUsh9cAR1JBYGin0jHTKOTW1)

###P3.5
![P3.5](https://drive.google.com/uc?id=1vvz0eCmEZHYAqcA0_Jk4RV1eogAKC3qf)

###P3.12
![P3.12](https://drive.google.com/uc?id=1KCqWYfy3WXm9Z3VCmF-tvU68rhuj7TTV)
![P3.12_1](https://drive.google.com/uc?id=1WcmVLLWqakirD323H23HitOs55Ob9yxn)
![P3.12_2](https://drive.google.com/uc?id=1Z0vcN-Y6ZVeuhwpTR6shzYlof3v2t2YP)

###P3.15
![P3.15_1](https://drive.google.com/uc?id=1IptG5B8gUBzNzb2M6gyMQKq94F5itpI9)
![P3.15_2](https://drive.google.com/uc?id=1sJby-wLeuzjSP5PthuWUvL-z1YSp5ETt)


```python
from google.colab import drive
drive.mount('/content/drive')
```

    Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

